version: '3.7'
services:
  postgresql:
    image: postgres:9.6
    restart: always
    container_name: copaDoMundo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5434:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data